all:
    hosts:
        Mb:
            ansible_host: 10.64.1.134
            ansible_user: ic293
            ansible_ssh_pass: Lysufe26
            ansible_port: 22
        Mc:
            ansible_host: 10.64.1.241
            ansible_user: ic2932
            ansible_ssh_pass: Lysufe26
            ansible_port: 22
