- name: Install package
  hosts: all
  vars:
    package_name: "{{ pkg_name }}"
    package_manager: "{{ pkg_mgr }}"
    package_state: "{{state}}"
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
    when: package_manager == "apt"
    register: apt_result
  - name: Install package
    apt:
      name: "{{ package_name }}"
      state: "{{ package_state }}"
    when: package_manager == "apt"
    register: apt_result
  - name: Install package
    pip:
      name: "{{ package_name }}"
      state: "{{ package_state }}"
    when: package_manager == "pip"
    register: pip_result
  - name: Print output
    debug:
      msg: "stdout: {{ pip_result.stdout }}, stderr: {{ pip_result.stderr }}, rc: {{ pip_result.changed }}"
    when: package_manager == "pip"
  - name: Print output
    debug:
      msg: "stdout: {{ apt_result.stdout }}, stderr: {{ apt_result.stderr }}, rc: {{ apt_result.rc }}"
    when: package_manager == "apt"


